repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.15
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
      args: ['--config=.flake8']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670-1
    hooks:
    - id: mypy


exclude: '^venv'
